# Generated by Django 3.2.8 on 2021-10-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_user', '0002_auto_20211029_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='permission',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_key',
            field=models.CharField(max_length=100),
        ),
    ]
