# Generated by Django 3.2.8 on 2021-10-31 12:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('domain_user', '0005_auto_20211031_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_key',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
