# Generated by Django 3.2.8 on 2021-10-29 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain_user', '0003_auto_20211030_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIDtoDomainMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=255)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_user.domain')),
            ],
            options={
                'db_table': 'vid_domain_map',
            },
        ),
    ]
