# Generated by Django 3.2.8 on 2021-10-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidtodomainmap',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
